services:
  frontend:
    image: ghcr.io/riccardo-modina/pileup-frontend:latest
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8080}
    #    ports:
    #      - "5173:80"
    depends_on:
      - backend
    networks:
      - pileup_internal

  backend:
    image: ghcr.io/riccardo-modina/pileup-backend:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - pileup_internal

  database:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - postgres_data_financeapp:/var/lib/postgresql/data
    networks:
      - pileup_internal

volumes:
  postgres_data_financeapp:

networks:
  pileup_internal:
    driver: bridge
