name: Backend Publish

on:
  push:
    tags:
      - 'backend-*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lowercase repo owner & extract version
        id: meta
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          CLEAN_VERSION="${GITHUB_REF_NAME#backend-}"
          echo "clean_version=${CLEAN_VERSION}" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/pileup-backend:latest
            ghcr.io/${{ env.REPO_OWNER }}/pileup-backend:${{ github.ref_name }}
            ghcr.io/${{ env.REPO_OWNER }}/pileup-backend:${{ steps.meta.outputs.clean_version }}
